### ISSUE TITLE
NRFX_TIMER1_INST_IDX undeclared when building for Holyiot

### ISSUE THREAD

**Issue by Artefact2** [SlimeVR/SlimeVR-Tracker-nRF-Receiver#31]
~~~
C:/ncs/v3.1.0/modules/hal/nordic/nrfx/drivers/include/nrfx_timer.h:65:37: error: 'NRFX_TIMER1_INST_IDX' undeclared here (not in a function); did you mean 'NRFX_TIMER2_INST_IDX'?
   65 |     .instance_id      = NRFX_CONCAT(NRFX_TIMER, id, _INST_IDX),   \
      |                                     ^~~~~~~~~~
~~~

Can be worked around by setting `CONFIG_NRFX_TIMER1=y` in `prj.conf`.

**Comment by sctanf** [comment]
expected to compile with sdk 3.2.0, there are some remaining issues currently
